# Generated by Django 5.0.2 on 2025-11-17 20:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título del curso",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL amigable generada automáticamente",
                        max_length=250,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada del curso",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Resumen breve para mostrar en listas",
                        max_length=300,
                        verbose_name="Descripción corta",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Principiante"),
                            ("elementary", "Elemental"),
                            ("intermediate", "Intermedio"),
                            ("upper_intermediate", "Intermedio Superior"),
                            ("advanced", "Avanzado"),
                            ("proficiency", "Competencia"),
                        ],
                        default="beginner",
                        help_text="Nivel de dificultad del curso",
                        max_length=20,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en-US",
                        help_text="Idioma principal del curso (ej: en-US, es-ES)",
                        max_length=10,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Precio del curso en USD",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio",
                    ),
                ),
                (
                    "fore_tokens_reward",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Tokens FORE que el estudiante recibe al completar el curso",
                        verbose_name="FORE Tokens de Recompensa",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de portada del curso (recomendado: 1280x720px)",
                        null=True,
                        upload_to="courses/thumbnails/",
                        verbose_name="Miniatura",
                    ),
                ),
                (
                    "trailer_video",
                    models.URLField(
                        blank=True,
                        help_text="URL del video promocional del curso",
                        null=True,
                        verbose_name="Video promocional",
                    ),
                ),
                (
                    "estimated_hours",
                    models.PositiveIntegerField(
                        help_text="Tiempo estimado para completar el curso",
                        verbose_name="Horas estimadas",
                    ),
                ),
                (
                    "max_enrollments",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Límite de estudiantes (vacío = sin límite)",
                        null=True,
                        verbose_name="Máximo de inscripciones",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar como curso destacado",
                        verbose_name="Curso destacado",
                    ),
                ),
                (
                    "enrollment_start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de inicio de inscripciones (vacío = siempre abierto)",
                        null=True,
                        verbose_name="Inicio de inscripciones",
                    ),
                ),
                (
                    "enrollment_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de fin de inscripciones",
                        null=True,
                        verbose_name="Fin de inscripciones",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Título para SEO (máx 60 caracteres)",
                        max_length=60,
                        verbose_name="Meta título",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Descripción para SEO (máx 160 caracteres)",
                        max_length=160,
                        verbose_name="Meta descripción",
                    ),
                ),
                (
                    "total_lessons",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número total de lecciones (calculado automáticamente)",
                        verbose_name="Total de lecciones",
                    ),
                ),
                (
                    "total_enrollments",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número total de inscripciones (calculado automáticamente)",
                        verbose_name="Total de inscripciones",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Calificación promedio del curso (0-5 estrellas)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación promedio",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        help_text="Profesor que imparte el curso",
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses_taught",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Instructor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("completed", "Completada"),
                            ("dropped", "Abandonada"),
                            ("suspended", "Suspendida"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Porcentaje de finalización del curso",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inscripción"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="Último acceso"),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Puntuación final",
                    ),
                ),
                (
                    "certificate_issued",
                    models.BooleanField(
                        default=False, verbose_name="Certificado emitido"
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL del certificado"
                    ),
                ),
                (
                    "fore_tokens_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="FORE Tokens ganados"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción en Curso",
                "verbose_name_plural": "Inscripciones en Cursos",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título de la lección",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL amigable generada automáticamente",
                        max_length=250,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la lección",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("text", "Texto"),
                            ("audio", "Audio"),
                            ("interactive", "Interactivo"),
                            ("quiz", "Cuestionario"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Tipo de lección",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Contenido de texto de la lección (Markdown soportado)",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL del video (YouTube, Vimeo, etc.)",
                        null=True,
                        verbose_name="URL del video",
                    ),
                ),
                (
                    "video_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duración en segundos",
                        null=True,
                        verbose_name="Duración del video (segundos)",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Archivo de audio para la lección",
                        null=True,
                        upload_to="lessons/audio/",
                        verbose_name="Archivo de audio",
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        help_text="PDFs, documentos, etc.",
                        null=True,
                        upload_to="lessons/attachments/",
                        verbose_name="Archivos adjuntos",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de la lección dentro del curso",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Tiempo estimado para completar la lección",
                        verbose_name="Duración estimada (minutos)",
                    ),
                ),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False,
                        help_text="Permitir vista previa gratuita de esta lección",
                        verbose_name="Vista previa",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="La lección es obligatoria para completar el curso",
                        verbose_name="Obligatoria",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Lección visible para los estudiantes",
                        verbose_name="Publicada",
                    ),
                ),
                (
                    "fore_tokens_reward",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Tokens FORE que el estudiante recibe al completar la lección",
                        verbose_name="FORE Tokens de Recompensa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "has_quiz",
                    models.BooleanField(
                        default=False,
                        help_text="Esta lección incluye un cuestionario",
                        verbose_name="Tiene cuestionario",
                    ),
                ),
                (
                    "completion_criteria",
                    models.CharField(
                        choices=[
                            ("view", "Solo ver"),
                            ("time", "Tiempo mínimo"),
                            ("quiz", "Completar cuestionario"),
                            ("interaction", "Interacción requerida"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="Criterio de finalización",
                    ),
                ),
                (
                    "min_completion_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tiempo mínimo que debe pasar en la lección",
                        null=True,
                        verbose_name="Tiempo mínimo (segundos)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lección",
                "verbose_name_plural": "Lecciones",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completada"),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiempo transcurrido (segundos)"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciada en"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completada en"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="Último acceso"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas del estudiante"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="courses.courseenrollment",
                        verbose_name="Inscripción",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Lección",
                "verbose_name_plural": "Progreso de Lecciones",
                "ordering": ["lesson__order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título del cuestionario",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Instrucciones o descripción del cuestionario",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tiempo límite en minutos (vacío = sin límite)",
                        null=True,
                        verbose_name="Tiempo límite (minutos)",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Número máximo de intentos permitidos",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Intentos máximos",
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=70,
                        help_text="Porcentaje mínimo para aprobar el cuestionario",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Puntuación mínima (%)",
                    ),
                ),
                (
                    "randomize_questions",
                    models.BooleanField(
                        default=True,
                        help_text="Mostrar las preguntas en orden aleatorio",
                        verbose_name="Aleatorizar preguntas",
                    ),
                ),
                (
                    "show_results_immediately",
                    models.BooleanField(
                        default=True,
                        help_text="Mostrar resultados al completar el cuestionario",
                        verbose_name="Mostrar resultados inmediatamente",
                    ),
                ),
                (
                    "allow_review",
                    models.BooleanField(
                        default=True,
                        help_text="Permitir revisar respuestas después de completar",
                        verbose_name="Permitir revisión",
                    ),
                ),
                (
                    "fore_tokens_reward",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Tokens FORE por aprobar el cuestionario",
                        verbose_name="FORE Tokens de Recompensa",
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número total de preguntas (calculado automáticamente)",
                        verbose_name="Total de preguntas",
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Puntuación promedio de todos los intentos",
                        max_digits=5,
                        verbose_name="Puntuación promedio",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuestionario",
                "verbose_name_plural": "Cuestionarios",
                "ordering": ["lesson__order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="El enunciado de la pregunta",
                        verbose_name="Texto de la pregunta",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Opción múltiple"),
                            ("true_false", "Verdadero/Falso"),
                            ("short_answer", "Respuesta corta"),
                            ("essay", "Ensayo"),
                            ("fill_blank", "Llenar espacios"),
                            ("matching", "Emparejar"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="Tipo de pregunta",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Puntos que vale esta pregunta",
                        verbose_name="Puntos",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de la pregunta en el cuestionario",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen asociada a la pregunta",
                        null=True,
                        upload_to="questions/images/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Archivo de audio para preguntas de listening",
                        null=True,
                        upload_to="questions/audio/",
                        verbose_name="Audio",
                    ),
                ),
                (
                    "option_a",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Opción A"
                    ),
                ),
                (
                    "option_b",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Opción B"
                    ),
                ),
                (
                    "option_c",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Opción C"
                    ),
                ),
                (
                    "option_d",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Opción D"
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="Respuesta correcta o clave de respuesta",
                        max_length=1000,
                        verbose_name="Respuesta correcta",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explicación de la respuesta correcta",
                        verbose_name="Explicación",
                    ),
                ),
                (
                    "is_case_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Para respuestas de texto, considerar mayúsculas/minúsculas",
                        verbose_name="Sensible a mayúsculas",
                    ),
                ),
                (
                    "partial_credit",
                    models.BooleanField(
                        default=False,
                        help_text="Permitir crédito parcial en respuestas aproximadas",
                        verbose_name="Crédito parcial",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.quiz",
                        verbose_name="Cuestionario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "ordering": ["quiz", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(verbose_name="Número de intento"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Puntuación",
                    ),
                ),
                (
                    "is_passed",
                    models.BooleanField(default=False, verbose_name="Aprobado"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completado"),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict,
                        help_text="Respuestas del estudiante en formato JSON",
                        verbose_name="Respuestas",
                    ),
                ),
                (
                    "time_taken",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tiempo empleado (segundos)"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado en"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado en"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="courses.courseenrollment",
                        verbose_name="Inscripción",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="courses.quiz",
                        verbose_name="Cuestionario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de Cuestionario",
                "verbose_name_plural": "Intentos de Cuestionarios",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["level", "status"], name="courses_cou_level_547ba0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["instructor", "status"], name="courses_cou_instruc_98570d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_featured", "status"], name="courses_cou_is_feat_a185b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["student", "status"], name="courses_cou_student_5a794f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["course", "status"], name="courses_cou_course__4e6f05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["enrolled_at"], name="courses_cou_enrolle_89b743_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseenrollment",
            unique_together={("student", "course")},
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["course", "order"], name="courses_les_course__dc0bc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["course", "is_published"], name="courses_les_course__acf0a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["lesson_type"], name="courses_les_lesson__299384_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("course", "order")},
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["enrollment", "is_completed"],
                name="courses_les_enrollm_1a9f99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["lesson", "is_completed"], name="courses_les_lesson__9e8ecb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("enrollment", "lesson")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["quiz", "order"], name="courses_que_quiz_id_d60549_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type"], name="courses_que_questio_beffac_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("quiz", "order")},
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["enrollment", "quiz"], name="courses_qui_enrollm_0ca656_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["quiz", "is_completed"], name="courses_qui_quiz_id_6fa477_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizattempt",
            unique_together={("enrollment", "quiz", "attempt_number")},
        ),
    ]
