# Generated by Django 5.0.2 on 2025-11-17 20:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email único del usuario",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono del usuario",
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ingrese un número de teléfono válido",
                                regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Estudiante"),
                            ("teacher", "Profesor"),
                            ("admin", "Administrador"),
                        ],
                        default="student",
                        help_text="Rol del usuario en la plataforma",
                        max_length=10,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de perfil del usuario",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Descripción corta del usuario",
                        max_length=500,
                        verbose_name="Biografía",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("es", "Español"),
                            ("en", "English"),
                            ("pt", "Português"),
                            ("fr", "Français"),
                        ],
                        default="es",
                        max_length=10,
                        verbose_name="Idioma preferido",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Bogota",
                        help_text="Zona horaria del usuario",
                        max_length=50,
                        verbose_name="Zona horaria",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Recibir notificaciones por correo electrónico",
                        verbose_name="Notificaciones por email",
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Recibir notificaciones push en la app",
                        verbose_name="Notificaciones push",
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Principiante"),
                            ("elementary", "Elemental"),
                            ("intermediate", "Intermedio"),
                            ("upper_intermediate", "Intermedio Alto"),
                            ("advanced", "Avanzado"),
                            ("proficient", "Competente"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Nivel actual de inglés",
                    ),
                ),
                (
                    "total_study_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tiempo acumulado de estudio en minutos",
                        verbose_name="Tiempo total de estudio (minutos)",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Si el usuario ha verificado su email",
                        verbose_name="Usuario verificado",
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actividad"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
                    models.Index(fields=["role"], name="users_user_role_36d76d_idx"),
                    models.Index(
                        fields=["is_active"], name="users_user_is_acti_ddda02_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_user_created_cf865c_idx"
                    ),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
