# Generated by Django 5.0.2 on 2025-11-17 21:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Nombre del logro",
                        max_length=100,
                        verbose_name="Título",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada de cómo obtener el logro",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("learning", "Aprendizaje"),
                            ("progress", "Progreso"),
                            ("social", "Social"),
                            ("consistency", "Consistencia"),
                            ("mastery", "Dominio"),
                            ("special", "Especial"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronce"),
                            ("silver", "Plata"),
                            ("gold", "Oro"),
                            ("platinum", "Platino"),
                            ("diamond", "Diamante"),
                        ],
                        default="bronze",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen del logro (recomendado: 128x128px)",
                        null=True,
                        upload_to="achievements/icons/",
                        verbose_name="Icono",
                    ),
                ),
                (
                    "badge_color",
                    models.CharField(
                        default="#FFD700",
                        help_text="Color en formato hexadecimal (#RRGGBB)",
                        max_length=7,
                        verbose_name="Color del badge",
                    ),
                ),
                (
                    "fore_tokens_reward",
                    models.PositiveIntegerField(
                        help_text="Tokens FORE otorgados al obtener el logro",
                        verbose_name="Recompensa FORE",
                    ),
                ),
                (
                    "required_courses",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de cursos que se deben completar",
                        verbose_name="Cursos requeridos",
                    ),
                ),
                (
                    "required_lessons",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de lecciones que se deben completar",
                        verbose_name="Lecciones requeridas",
                    ),
                ),
                (
                    "required_quizzes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de quizzes que se deben aprobar",
                        verbose_name="Quizzes requeridos",
                    ),
                ),
                (
                    "required_streak_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Días consecutivos de actividad requeridos",
                        verbose_name="Días de racha requeridos",
                    ),
                ),
                (
                    "required_fore_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total de tokens FORE que se deben haber ganado",
                        verbose_name="FORE tokens requeridos",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si el logro está disponible para obtener",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False,
                        help_text="Los logros secretos no se muestran hasta obtenerlos",
                        verbose_name="Secreto",
                    ),
                ),
                (
                    "max_recipients",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Límite de usuarios que pueden obtener este logro",
                        null=True,
                        verbose_name="Máximo de receptores",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro",
                "verbose_name_plural": "Logros",
                "ordering": ["category", "achievement_type", "title"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="rewards_ach_categor_00795b_idx",
                    ),
                    models.Index(
                        fields=["achievement_type"],
                        name="rewards_ach_achieve_8a6859_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Nombre del ranking",
                        max_length=100,
                        verbose_name="Título",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del criterio de ranking",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fore_tokens", "FORE Tokens Ganados"),
                            ("courses_completed", "Cursos Completados"),
                            ("lessons_completed", "Lecciones Completadas"),
                            ("quizzes_passed", "Quizzes Aprobados"),
                            ("achievements_earned", "Logros Obtenidos"),
                            ("streak_days", "Días de Racha"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("all_time", "Todo el tiempo"),
                        ],
                        max_length=20,
                        verbose_name="Período",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "max_positions",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Número máximo de posiciones a mostrar",
                        verbose_name="Máximo de posiciones",
                    ),
                ),
                (
                    "first_place_reward",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="FORE tokens para el primer lugar",
                        verbose_name="Recompensa 1er lugar",
                    ),
                ),
                (
                    "second_place_reward",
                    models.PositiveIntegerField(
                        default=75,
                        help_text="FORE tokens para el segundo lugar",
                        verbose_name="Recompensa 2do lugar",
                    ),
                ),
                (
                    "third_place_reward",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="FORE tokens para el tercer lugar",
                        verbose_name="Recompensa 3er lugar",
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio del período"
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin del período"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking",
                "verbose_name_plural": "Rankings",
                "ordering": ["category", "period"],
                "indexes": [
                    models.Index(
                        fields=["category", "period"],
                        name="rewards_lea_categor_98141d_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="rewards_lea_is_acti_77bf54_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Nombre de la recompensa",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción detallada de la recompensa",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("physical", "Físico"),
                            ("experience", "Experiencia"),
                            ("education", "Educación"),
                            ("entertainment", "Entretenimiento"),
                            ("charity", "Caridad"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "fore_cost",
                    models.PositiveIntegerField(
                        help_text="Cantidad de tokens FORE necesarios",
                        verbose_name="Costo FORE",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de la recompensa",
                        null=True,
                        upload_to="rewards/images/",
                        verbose_name="Imagen",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cantidad disponible (vacío = ilimitado)",
                        null=True,
                        verbose_name="Cantidad en stock",
                    ),
                ),
                (
                    "max_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Límite de canjes por usuario",
                        null=True,
                        verbose_name="Máximo por usuario",
                    ),
                ),
                (
                    "available_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Disponible desde"
                    ),
                ),
                (
                    "available_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Disponible hasta"
                    ),
                ),
                (
                    "delivery_info",
                    models.TextField(
                        blank=True,
                        help_text="Instrucciones para reclamar/recibir la recompensa",
                        verbose_name="Información de entrega",
                    ),
                ),
                (
                    "requires_shipping",
                    models.BooleanField(
                        default=False,
                        help_text="Si requiere dirección de envío física",
                        verbose_name="Requiere envío",
                    ),
                ),
                (
                    "total_redeemed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número total de veces que se ha canjeado",
                        verbose_name="Total canjeado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recompensa",
                "verbose_name_plural": "Recompensas",
                "ordering": ["category", "fore_cost"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="rewards_rew_categor_1a6f56_idx",
                    ),
                    models.Index(
                        fields=["fore_cost"], name="rewards_rew_fore_co_7993f0_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="rewards_rew_is_acti_6b8e52_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FOREWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Balance actual de tokens FORE",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Balance FORE",
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total de tokens FORE ganados históricamente",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total ganado",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total de tokens FORE gastados históricamente",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total gastado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "frozen_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tokens temporalmente no disponibles",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Cantidad congelada",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fore_wallet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billetera FORE",
                "verbose_name_plural": "Billeteras FORE",
                "indexes": [
                    models.Index(
                        fields=["user"], name="rewards_for_user_id_b528fa_idx"
                    ),
                    models.Index(
                        fields=["balance"], name="rewards_for_balance_9441cf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fore_cost",
                    models.PositiveIntegerField(
                        help_text="Tokens FORE gastados en el momento del canje",
                        verbose_name="Costo FORE",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregado"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True,
                        help_text="Para recompensas físicas",
                        verbose_name="Dirección de entrega",
                    ),
                ),
                (
                    "delivery_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono de contacto"
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Código de seguimiento"
                    ),
                ),
                (
                    "redemption_code",
                    models.CharField(
                        blank=True,
                        help_text="Código único para reclamar la recompensa",
                        max_length=50,
                        verbose_name="Código de canje",
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de canje"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notas administrativas"),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="rewards.reward",
                        verbose_name="Recompensa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_redemptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canje de Recompensa",
                "verbose_name_plural": "Canjes de Recompensas",
                "ordering": ["-redeemed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-redeemed_at"],
                        name="rewards_rew_user_id_af88bd_idx",
                    ),
                    models.Index(
                        fields=["status"], name="rewards_rew_status_89631b_idx"
                    ),
                    models.Index(
                        fields=["reward"], name="rewards_rew_reward__7c6cf0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("lesson_completed", "Lección completada"),
                            ("quiz_passed", "Quiz aprobado"),
                            ("course_completed", "Curso completado"),
                            ("achievement_earned", "Logro obtenido"),
                            ("daily_login", "Login diario"),
                            ("referral_bonus", "Bonus por referido"),
                            ("admin_bonus", "Bonus administrativo"),
                            ("reward_purchase", "Compra de recompensa"),
                            ("premium_feature", "Función premium"),
                            ("marketplace_purchase", "Compra en marketplace"),
                            ("transfer_in", "Transferencia recibida"),
                            ("transfer_out", "Transferencia enviada"),
                            ("refund", "Reembolso"),
                            ("adjustment", "Ajuste manual"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de transacción",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad de tokens (positiva para ganancias, negativa para gastos)",
                        max_digits=12,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Balance total después de la transacción",
                        max_digits=12,
                        verbose_name="Balance después",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de la transacción",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de transacción"
                    ),
                ),
                (
                    "created_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fore_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creada por admin",
                    ),
                ),
                (
                    "related_achievement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rewards.achievement",
                        verbose_name="Logro relacionado",
                    ),
                ),
                (
                    "related_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                        verbose_name="Curso relacionado",
                    ),
                ),
                (
                    "related_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.lesson",
                        verbose_name="Lección relacionada",
                    ),
                ),
                (
                    "related_quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.quiz",
                        verbose_name="Quiz relacionado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fore_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción FORE",
                "verbose_name_plural": "Transacciones FORE",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="rewards_tra_user_id_ac3768_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="rewards_tra_transac_cf4917_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="rewards_tra_created_0dfa00_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Obtenido en"),
                ),
                (
                    "fore_tokens_awarded",
                    models.PositiveIntegerField(
                        help_text="Cantidad de tokens otorgados al obtener el logro",
                        verbose_name="FORE tokens otorgados",
                    ),
                ),
                (
                    "progress_when_earned",
                    models.JSONField(
                        default=dict,
                        help_text="Estadísticas del usuario al momento de obtener el logro",
                        verbose_name="Progreso al obtener",
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="rewards.achievement",
                        verbose_name="Logro",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements_earned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro de Usuario",
                "verbose_name_plural": "Logros de Usuarios",
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-earned_at"],
                        name="rewards_use_user_id_d56a94_idx",
                    ),
                    models.Index(
                        fields=["achievement"], name="rewards_use_achieve_175a2f_idx"
                    ),
                ],
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="UserRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(verbose_name="Posición")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Puntuación"
                    ),
                ),
                (
                    "reward_claimed",
                    models.BooleanField(
                        default=False, verbose_name="Recompensa reclamada"
                    ),
                ),
                (
                    "reward_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad de recompensa"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "leaderboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_rankings",
                        to="rewards.leaderboard",
                        verbose_name="Ranking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_positions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posición en Ranking",
                "verbose_name_plural": "Posiciones en Rankings",
                "ordering": ["leaderboard", "position"],
                "indexes": [
                    models.Index(
                        fields=["leaderboard", "position"],
                        name="rewards_use_leaderb_1b9c33_idx",
                    ),
                    models.Index(
                        fields=["user"], name="rewards_use_user_id_0167e0_idx"
                    ),
                ],
                "unique_together": {
                    ("leaderboard", "position"),
                    ("leaderboard", "user"),
                },
            },
        ),
    ]
